# Generated by Django 5.2.12 on 2026-04-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_booking_is_paid_booking_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
